### ISSUE TITLE
Application does not quit via File > Quit (or Cmd+Q) in macOS

### ISSUE THREAD

**Issue by willkill07** [mucsci-students/2022sp-420-NotJava#169]
Only clicking "X" on the window disposes of the application.

**Comment by Robunnin** [comment]
(Notes for the team)
I had a really hard time finding documentation on how to use the NativeMenu. It is basically nonexistent on Avalonia's website and either outdated or lacking detail on other sites. Most of my findings were just trial and error until something worked. I'll post them here to save us the time it took me.

NOTE: This is for macOS only

By default, the main NativeMenu is titled "AvaloniaApplication". To change this, edit the Name property within the Application tag in _**App.axaml**_. I suggest using "UML Editor" as the title for this menu. 

Menu items can be added to this NativeMenu in a very similar manner to our in-window title bar. To do so, you have to add this in App.axaml:

```
<NativeMenu.Menu>
        <NativeMenu>
               <NativeMenuItem Header="EXIT EDITOR" Gesture="cmd+q" Click="NativeMenuItem_OnClick"/>
	</NativeMenu>
</NativeMenu.Menu>
```

This will add a menu entry to the main NativeMenu called "EXIT EDITOR". The Gesture allows you to specify a keyboard combo to invoke the menu command. The binding is just the same for any other button or menu, the handler just needs to be in App.axaml.cs and do the same thing as the quit command in MainWindow.

I don't know how to add other menus like "File" to the menu bar (and I was not able to find documentation on this when I wrote this). You can't have multiple NativeMenu tags. Maybe this is okay since we use the in-window menu more heavily.

**Comment by gfry99** [comment]
We also want to move exit to the file menu item.
